export const APP_ROUTE = 'APP_ROUTE';

export const LAYOUT_HEADER_PROFILE = 'LAYOUT_HEADER_PROFILE';
export const LAYOUT_HEADER_APPS = 'LAYOUT_HEADER_APPS';

export const EVENT_HEADER_APPS_CLICKED = 'EVENT_HEADER_APPS_CLICKED';
export const EVENT_HEADER_PROFILE_CLICKED = 'EVENT_HEADER_PROFILE_CLICKED';
